model:
  source: ".model/dolphin-2.2.1-mistral-7b.Q4_K_M.gguf"
max_context_length: 8192
stop_tokens:
  - "</s>"
  - "<|im_end|>"
prompt_format:
  chat:
    system: "<|im_start|>system\n{}<|im_end|>\n"
    assistant: "<|im_start|>assistant\n{}<|im_end|>\n"
    user: "<|im_start|>user\n{}<|im_end|>\n"
defaults:
  top_p: 1.0
  top_k: 0