package:
  create:
    set:
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/llamacpp"
      image_version: 0.0.1
      name: llamacpp
    max_package_size: "1000000000"
  deploy:
    set:
      limits_cpu: 1
      limits_memory: 20Gi
      limits_gpu: 1
      requests_cpu: 1
      requests_memory: 4Gi
      requests_gpu: 1
      name: llamacpp
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/llamacpp"
      image_version: 0.0.1