package:
  create:
    set:
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/llama-cpp-python"
      image_version: 0.2.0
      name: llama-cpp-python
    max_package_size: "1000000000"
  deploy:
    set:
      name: llama-cpp-python
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/llama-cpp-python"
      image_version: 0.2.0
      limits_cpu: 1
      limits_memory: 20Gi
      limits_gpu: 0
      requests_cpu: 1
      requests_memory: 4Gi
      requests_gpu: 0